"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.luftqualitaet.api.airquality_api import AirqualityApi  # noqa: E501

from deutschland import luftqualitaet


class TestAirqualityApi(unittest.TestCase):
    """AirqualityApi unit test stubs"""

    def setUp(self):
        self.api = AirqualityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_airquality_json_get(self):
        """Test case for airquality_json_get

        Get airquality data  # noqa: E501
        """
        pass

    def test_airquality_limits_get(self):
        """Test case for airquality_limits_get

        Get airquality date limits  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
