"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.luftqualitaet.api.exceedances_api import ExceedancesApi  # noqa: E501

from deutschland import luftqualitaet


class TestExceedancesApi(unittest.TestCase):
    """ExceedancesApi unit test stubs"""

    def setUp(self):
        self.api = ExceedancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transgressions_json_get(self):
        """Test case for transgressions_json_get

        Get exceedances data  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
