"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.component import Component

from deutschland import luftqualitaet

globals()["Component"] = Component
from deutschland.luftqualitaet.model.inline_response2006_components import (
    InlineResponse2006Components,
)


class TestInlineResponse2006Components(unittest.TestCase):
    """InlineResponse2006Components unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006Components(self):
        """Test InlineResponse2006Components"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006Components()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
