"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.annualbalance import Annualbalance

from deutschland import luftqualitaet

globals()["Annualbalance"] = Annualbalance
from deutschland.luftqualitaet.model.inline_response2002 import InlineResponse2002


class TestInlineResponse2002(unittest.TestCase):
    """InlineResponse2002 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002(self):
        """Test InlineResponse2002"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2002()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
