"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.limit import Limit

from deutschland import luftqualitaet


class TestLimit(unittest.TestCase):
    """Limit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLimit(self):
        """Test Limit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Limit()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
