"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.measurelimit import Measurelimit

from deutschland import luftqualitaet


class TestMeasurelimit(unittest.TestCase):
    """Measurelimit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurelimit(self):
        """Test Measurelimit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Measurelimit()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
