"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.scope import Scope

from deutschland import luftqualitaet

globals()["Scope"] = Scope
from deutschland.luftqualitaet.model.inline_response2006_scopes import (
    InlineResponse2006Scopes,
)


class TestInlineResponse2006Scopes(unittest.TestCase):
    """InlineResponse2006Scopes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006Scopes(self):
        """Test InlineResponse2006Scopes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006Scopes()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
