"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.luftqualitaet.api.annualtabulation_api import (  # noqa: E501
    AnnualtabulationApi,
)

from deutschland import luftqualitaet


class TestAnnualtabulationApi(unittest.TestCase):
    """AnnualtabulationApi unit test stubs"""

    def setUp(self):
        self.api = AnnualtabulationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_annualbalances_json_get(self):
        """Test case for annualbalances_json_get

        Get annualtabulation  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
