"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.station import Station

from deutschland import luftqualitaet

globals()["Station"] = Station
from deutschland.luftqualitaet.model.inline_response2006_stations import (
    InlineResponse2006Stations,
)


class TestInlineResponse2006Stations(unittest.TestCase):
    """InlineResponse2006Stations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006Stations(self):
        """Test InlineResponse2006Stations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006Stations()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
