"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.inline_response2006_xref import (
    InlineResponse2006Xref,
)

from deutschland import luftqualitaet


class TestInlineResponse2006Xref(unittest.TestCase):
    """InlineResponse2006Xref unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006Xref(self):
        """Test InlineResponse2006Xref"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006Xref()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
