"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.airquality_date_start_cet3_and_following import (
    AirqualityDateStartCET3AndFollowing,
)

from deutschland import luftqualitaet


class TestAirqualityDateStartCET3AndFollowing(unittest.TestCase):
    """AirqualityDateStartCET3AndFollowing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAirqualityDateStartCET3AndFollowing(self):
        """Test AirqualityDateStartCET3AndFollowing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AirqualityDateStartCET3AndFollowing()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
