"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.airquality_station_id import AirqualityStationId

from deutschland import luftqualitaet

globals()["AirqualityStationId"] = AirqualityStationId
from deutschland.luftqualitaet.model.airquality import Airquality


class TestAirquality(unittest.TestCase):
    """Airquality unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAirquality(self):
        """Test Airquality"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Airquality()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
