"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.airqualitylimits_station_id import (
    AirqualitylimitsStationId,
)

from deutschland import luftqualitaet

globals()["AirqualitylimitsStationId"] = AirqualitylimitsStationId
from deutschland.luftqualitaet.model.airqualitylimits import Airqualitylimits


class TestAirqualitylimits(unittest.TestCase):
    """Airqualitylimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAirqualitylimits(self):
        """Test Airqualitylimits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Airqualitylimits()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
