"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.inline_response2006_components import (
    InlineResponse2006Components,
)
from deutschland.luftqualitaet.model.inline_response2006_limits1 import (
    InlineResponse2006Limits1,
)
from deutschland.luftqualitaet.model.inline_response2006_limits2 import (
    InlineResponse2006Limits2,
)
from deutschland.luftqualitaet.model.inline_response2006_networks import (
    InlineResponse2006Networks,
)
from deutschland.luftqualitaet.model.inline_response2006_scopes import (
    InlineResponse2006Scopes,
)
from deutschland.luftqualitaet.model.inline_response2006_stations import (
    InlineResponse2006Stations,
)
from deutschland.luftqualitaet.model.inline_response2006_xref import (
    InlineResponse2006Xref,
)

from deutschland import luftqualitaet

globals()["InlineResponse2006Components"] = InlineResponse2006Components
globals()["InlineResponse2006Limits1"] = InlineResponse2006Limits1
globals()["InlineResponse2006Limits2"] = InlineResponse2006Limits2
globals()["InlineResponse2006Networks"] = InlineResponse2006Networks
globals()["InlineResponse2006Scopes"] = InlineResponse2006Scopes
globals()["InlineResponse2006Stations"] = InlineResponse2006Stations
globals()["InlineResponse2006Xref"] = InlineResponse2006Xref
from deutschland.luftqualitaet.model.inline_response2006 import InlineResponse2006


class TestInlineResponse2006(unittest.TestCase):
    """InlineResponse2006 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006(self):
        """Test InlineResponse2006"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2006()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
