"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.stationsetting import Stationsetting

from deutschland import luftqualitaet


class TestStationsetting(unittest.TestCase):
    """Stationsetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationsetting(self):
        """Test Stationsetting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Stationsetting()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
