"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.measurelimit import Measurelimit

from deutschland import luftqualitaet

globals()["Measurelimit"] = Measurelimit
from deutschland.luftqualitaet.model.inline_response2004_data import (
    InlineResponse2004Data,
)


class TestInlineResponse2004Data(unittest.TestCase):
    """InlineResponse2004Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004Data(self):
        """Test InlineResponse2004Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2004Data()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
