"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.luftqualitaet.api.measurements_api import MeasurementsApi  # noqa: E501

from deutschland import luftqualitaet


class TestMeasurementsApi(unittest.TestCase):
    """MeasurementsApi unit test stubs"""

    def setUp(self):
        self.api = MeasurementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_measures_json_get(self):
        """Test case for measures_json_get

        Get all measurements  # noqa: E501
        """
        pass

    def test_measures_limits_get(self):
        """Test case for measures_limits_get

        Get measurement date limits  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
