"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.annualbalance import Annualbalance

from deutschland import luftqualitaet


class TestAnnualbalance(unittest.TestCase):
    """Annualbalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnualbalance(self):
        """Test Annualbalance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Annualbalance()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
