"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.stationtype import Stationtype

from deutschland import luftqualitaet


class TestStationtype(unittest.TestCase):
    """Stationtype unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationtype(self):
        """Test Stationtype"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Stationtype()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
