"""
    Umweltbundesamt Air Data API

    Air data API of Umweltbundesamt  # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: immission@uba.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.luftqualitaet.model.airquality_date_start_cet import (
    AirqualityDateStartCET,
)

from deutschland import luftqualitaet

globals()["AirqualityDateStartCET"] = AirqualityDateStartCET
from deutschland.luftqualitaet.model.airquality_station_id import AirqualityStationId


class TestAirqualityStationId(unittest.TestCase):
    """AirqualityStationId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAirqualityStationId(self):
        """Test AirqualityStationId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AirqualityStationId()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
